#import libraries
import pandas as pd
import numpy as np


In [33]:
# Create row data
file = {
    "Name":["Sahil","Rahul","Aman","priya","Naha"],
    "Age":[20,21,19,20,22],
    "Maths":[85,78,92,88,75],
    "Department":["Data Science","Computer Science","Data Science","Computer Science","Data Science"]
}


In [34]:
student_makes = pd.DataFrame(file)
print(student_makes)

    Name  Age  Maths        Department
0  Sahil   20     85      Data Science
1  Rahul   21     78  Computer Science
2   Aman   19     92      Data Science
3  priya   20     88  Computer Science
4   Naha   22     75      Data Science


In [35]:
print("First 5 rows :\n",student_makes.head())
print("Data type :\n",student_makes.dtypes)
print("\nshape :",student_makes.shape)

First 5 rows :
     Name  Age  Maths        Department
0  Sahil   20     85      Data Science
1  Rahul   21     78  Computer Science
2   Aman   19     92      Data Science
3  priya   20     88  Computer Science
4   Naha   22     75      Data Science
Data type :
 Name            str
Age           int64
Maths         int64
Department      str
dtype: object

shape : (5, 4)


In [36]:
numeric_data =student_makes[['Age','Maths']].values
print(numeric_data)

[[20 85]
 [21 78]
 [19 92]
 [20 88]
 [22 75]]


In [37]:
print("shape : ",numeric_data.shape)
print("size : ",numeric_data.size)
print("dimension : ",numeric_data.ndim)

shape :  (5, 2)
size :  10
dimension :  2


In [38]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[1,12],
              [8,4]])
print("Matrix A:\n",A,"\nMatrix B:\n",B)

Matrix A:
 [[1 2]
 [3 4]] 
Matrix B:
 [[ 1 12]
 [ 8  4]]


In [39]:
print("Addition:\n",A+B)
print("substraction :\n",A-B)
print("Multiplication :\n",A*B)
print("Dot product :\n",np.dot(A,B))
print('Transpose of A :\n',A.T)
print("Inverse of A :\n",np.linalg.inv(A))
print('Determinant of A: \n ',np.linalg.det(A))

#convert string data into numerical data
encoded_student_marks_department =pd.get_dummies(
    student_makes,
    columns=["Department"],
    dtype=int
)
print("\nOne-Hot Encoded Data:")
print(encoded_student_marks_department)

Addition:
 [[ 2 14]
 [11  8]]
substraction :
 [[  0 -10]
 [ -5   0]]
Multiplication :
 [[ 1 24]
 [24 16]]
Dot product :
 [[17 20]
 [35 52]]
Transpose of A :
 [[1 3]
 [2 4]]
Inverse of A :
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: 
  -2.0000000000000004

One-Hot Encoded Data:
    Name  Age  Maths  Department_Computer Science  Department_Data Science
0  Sahil   20     85                            0                        1
1  Rahul   21     78                            1                        0
2   Aman   19     92                            0                        1
3  priya   20     88                            1                        0
4   Naha   22     75                            0                        1
